title: Tiina Koho
description: This page is an assignment to the course 'Command-line Course' (KIK-LG218), at the University of Helsinki.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
